SET IDENTITY_INSERT [dbo].[Tapes] ON
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (1, N'RS0001L6', 4, 5, 1, NULL, N'WEEK 1 CAD TAPE 1', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (2, N'RS0002L6', 4, 5, 1, NULL, N'WEEK 1 CAD TAPE 2', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (3, N'RS0003L6', 4, 5, 1, NULL, N'WEEK 1 CAD TAPE 3', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (4, N'RS0004L6', 5, 5, 1, NULL, N'WEEK 1 CAD TAPE 4', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (5, N'RS0005L6', 5, 5, 1, NULL, N'WEEK 1 CAD TAPE 5', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (6, N'RS0006L6', 5, 5, 1, NULL, N'WEEK 1 CAD TAPE 6', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (7, N'RS0007L6', 4, 5, 2, NULL, N'WEEK 2 CAD TAPE 1', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (8, N'RS0008L6', 4, 5, 2, NULL, N'WEEK 2 CAD TAPE 2', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (9, N'RS0009L6', 4, 5, 2, NULL, N'WEEK 2 CAD TAPE 3', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (10, N'RS0010L6', 5, 5, 2, NULL, N'WEEK 2 CAD TAPE 4', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (11, N'RS0011L6', 5, 5, 2, NULL, N'WEEK 2 CAD TAPE 5', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (12, N'RS0012L6', 5, 5, 2, NULL, N'WEEK 2 CAD TAPE 6', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (13, N'RS0013L6', 4, 5, 3, NULL, N'WEEK 3 CAD TAPE 1', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (14, N'RS0014L6', 4, 5, 3, NULL, N'WEEK 3 CAD TAPE 2', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (15, N'RS0015L6', 4, 5, 3, NULL, N'WEEK 3 CAD TAPE 3', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (16, N'RS0016L6', 5, 5, 3, NULL, N'WEEK 3 CAD TAPE 4', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (17, N'RS0017L6', 5, 5, 3, NULL, N'WEEK 3 CAD TAPE 5', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (18, N'RS0018L6', 5, 5, 3, NULL, N'WEEK 3 CAD TAPE 6', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (19, N'RS0019L6', 4, 5, 4, NULL, N'WEEK 4 CAD TAPE 1', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (20, N'RS0020L6', 4, 5, 4, NULL, N'WEEK 4 CAD TAPE 2', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (21, N'RS0021L6', 4, 5, 4, NULL, N'WEEK 4 CAD TAPE 3', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (22, N'RS0022L6', 5, 5, 4, NULL, N'WEEK 4 CAD TAPE 4', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (23, N'RS0023L6', 5, 5, 4, NULL, N'WEEK 4 CAD TAPE 5', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (24, N'RS0024L6', 5, 5, 4, NULL, N'WEEK 4 CAD TAPE 6', 2)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (25, N'RS0025L6', 3, 1, NULL, NULL, N'DAY 1 CAD TAPE 1', 1)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (26, N'RS0026L6', 3, 1, NULL, NULL, N'DAY 2 CAD TAPE 1', 1)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (27, N'RS0027L6', 3, 1, NULL, NULL, N'DAY 3 CAD TAPE 1', 1)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (28, N'RS0028L6', 3, 1, NULL, NULL, N'DAY 4 CAD TAPE 1', 1)

INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (29, N'RS0029L6', 4, 5, NULL, 1, N'JANUARY CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (30, N'RS0030L6', 4, 5, NULL, 1, N'JANUARY CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (31, N'RS0031L6', 4, 5, NULL, 1, N'JANUARY CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (32, N'RS0032L6', 5, 5, NULL, 1, N'JANUARY CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (33, N'RS0033L6', 5, 5, NULL, 1, N'JANUARY CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (34, N'RS0034L6', 5, 5, NULL, 1, N'JANUARY CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (35, N'RS0035L6', 4, 5, NULL, 2, N'FEBRUARY CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (36, N'RS0036L6', 4, 5, NULL, 2, N'FEBRUARY CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (37, N'RS0037L6', 4, 5, NULL, 2, N'FEBRUARY CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (38, N'RS0038L6', 5, 5, NULL, 2, N'FEBRUARY CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (39, N'RS0039L6', 5, 5, NULL, 2, N'FEBRUARY CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (40, N'RS0040L6', 5, 5, NULL, 2, N'FEBRUARY CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (41, N'RS0041L6', 4, 5, NULL, 3, N'MARCH CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (42, N'RS0042L6', 4, 5, NULL, 3, N'MARCH CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (43, N'RS0043L6', 4, 5, NULL, 3, N'MARCH CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (44, N'RS0044L6', 5, 5, NULL, 3, N'MARCH CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (45, N'RS0045L6', 5, 5, NULL, 3, N'MARCH CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (46, N'RS0046L6', 5, 5, NULL, 3, N'MARCH CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (47, N'RS0047L6', 4, 5, NULL, 4, N'APRIL CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (48, N'RS0048L6', 4, 5, NULL, 4, N'APRIL CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (49, N'RS0049L6', 4, 5, NULL, 4, N'APRIL CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (50, N'RS0050L6', 5, 5, NULL, 4, N'APRIL CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (51, N'RS0051L6', 5, 5, NULL, 4, N'APRIL CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (52, N'RS0052L6', 5, 5, NULL, 4, N'APRIL CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (53, N'RS0053L6', 4, 5, NULL, 5, N'APRIL CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (54, N'RS0054L6', 4, 5, NULL, 5, N'MAY CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (55, N'RS0055L6', 4, 5, NULL, 5, N'MAY CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (56, N'RS0056L6', 5, 5, NULL, 5, N'MAY CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (57, N'RS0057L6', 5, 5, NULL, 5, N'MAY CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (58, N'RS0058L6', 5, 5, NULL, 5, N'MAY CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (59, N'RS0059L6', 4, 5, NULL, 6, N'JUNE CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (60, N'RS0060L6', 4, 5, NULL, 6, N'JUNE CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (61, N'RS0061L6', 4, 5, NULL, 6, N'JUNE CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (62, N'RS0061L6', 5, 5, NULL, 6, N'JUNE CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (63, N'RS0063L6', 5, 5, NULL, 6, N'JUNE CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (64, N'RS0064L6', 5, 5, NULL, 6, N'JUNE CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (65, N'RS0065L6', 4, 5, NULL, 7, N'JULY CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (66, N'RS0066L6', 4, 5, NULL, 7, N'JULY CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (67, N'RS0067L6', 4, 5, NULL, 7, N'JULY CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (68, N'RS0068L6', 5, 5, NULL, 7, N'JULY CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (69, N'RS0069L6', 5, 5, NULL, 7, N'JULY CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (70, N'RS0070L6', 5, 5, NULL, 7, N'JULY CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (71, N'RS0071L6', 4, 5, NULL, 8, N'AUGUST CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (72, N'RS0072L6', 4, 5, NULL, 8, N'AUGUST CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (73, N'RS0073L6', 4, 5, NULL, 8, N'AUGUST CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (74, N'RS0074L6', 5, 5, NULL, 8, N'AUGUST CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (75, N'RS0075L6', 5, 5, NULL, 8, N'AUGUST CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (76, N'RS0076L6', 5, 5, NULL, 8, N'AUGUST CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (77, N'RS0077L6', 4, 5, NULL, 9, N'SEPTEMBER CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (78, N'RS0078L6', 4, 5, NULL, 9, N'SEPTEMBER CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (79, N'RS0079L6', 4, 5, NULL, 9, N'SEPTEMBER CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (80, N'RS0080L6', 5, 5, NULL, 9, N'SEPTEMBER CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (81, N'RS0081L6', 5, 5, NULL, 9, N'SEPTEMBER CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (82, N'RS0082L6', 5, 5, NULL, 9, N'SEPTEMBER CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (83, N'RS0083L6', 4, 5, NULL, 10, N'OCTOBER CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (84, N'RS0084L6', 4, 5, NULL, 10, N'OCTOBER CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (85, N'RS0085L6', 4, 5, NULL, 10, N'OCTOBER CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (86, N'RS0086L6', 5, 5, NULL, 10, N'OCTOBER CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (87, N'RS0087L6', 5, 5, NULL, 10, N'OCTOBER CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (88, N'RS0088L6', 5, 5, NULL, 10, N'OCTOBER CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (89, N'RS0089L6', 4, 5, NULL, 11, N'NOVEMBER CAD TAPE 1', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (90, N'RS0090L6', 4, 5, NULL, 11, N'NOVEMBER CAD TAPE 2', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (91, N'RS0091L6', 4, 5, NULL, 11, N'NOVEMBER CAD TAPE 3', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (92, N'RS0092L6', 5, 5, NULL, 11, N'NOVEMBER CAD TAPE 4', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (93, N'RS0093L6', 5, 5, NULL, 11, N'NOVEMBER CAD TAPE 5', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (94, N'RS0094L6', 5, 5, NULL, 11, N'NOVEMBER CAD TAPE 6', 3)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (95, N'RS0095L6', 4, 5, NULL, 12, N'DECEMBER CAD TAPE 1', 4)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (96, N'RS0096L6', 4, 5, NULL, 12, N'DECEMBER CAD TAPE 2', 4)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (97, N'RS0097L6', 4, 5, NULL, 12, N'DECEMBER CAD TAPE 3', 4)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (98, N'RS0098L6', 5, 5, NULL, 12, N'DECEMBER CAD TAPE 4', 4)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (99, N'RS0099L6', 5, 5, NULL, 12, N'DECEMBER CAD TAPE 5', 4)
INSERT INTO [dbo].[Tapes] ([Id], [BarCode], [BackupSystemId], [DayId], [WeekId], [MonthId], [Details], [BackupTypesId]) VALUES (100, N'RS0100L6', 5, 5, NULL, 12, N'DECEMBER CAD TAPE 6', 4)


SET IDENTITY_INSERT [dbo].[Tapes] OFF
