// <auto-generated />
namespace BackupManagementApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TestValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202110311657518_TestValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
